import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const IPHONE_16_WIDTH = 430; // iPhone 16 Pro Max width in pt
const SCALE = width / IPHONE_16_WIDTH;

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FEFBFB',
    paddingTop: 60 * SCALE,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 24 * SCALE,
    marginBottom: 32 * SCALE,
  },
  headerIcon: {
    width: 35 * SCALE,
    height: 35 * SCALE,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontFamily: 'Inter',
    fontSize: 20 * SCALE,
    color: '#000',
    fontWeight: 'bold',
  },
  plantImageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 180 * SCALE,
    height: 180 * SCALE,
    borderRadius: 90 * SCALE,
    backgroundColor: '#fff',
    alignSelf: 'center',
    overflow: 'hidden',
    marginBottom: 18 * SCALE,
  },
  plantImage: {
    width: 180 * SCALE,
    height: 180 * SCALE,
    borderRadius: 90 * SCALE,
  },
  plantTitle: {
    fontFamily: 'Inter',
    fontSize: 20 * SCALE,
    color: '#000',
    fontWeight: '400',
    textAlign: 'center',
    marginBottom: 2 * SCALE,
  },
  plantSubtitle: {
    fontFamily: 'Inter',
    fontSize: 12 * SCALE,
    color: '#717171',
    fontWeight: '400',
    textAlign: 'center',
    marginBottom: 24 * SCALE,
  },
  descriptionContainer: {
    paddingHorizontal: 24 * SCALE,
    marginBottom: 24 * SCALE,
  },
  descriptionTitle: {
    fontFamily: 'Inter',
    fontSize: 18 * SCALE,
    color: '#000',
    fontWeight: 'bold',
    marginBottom: 8 * SCALE,
  },
  descriptionText: {
    fontFamily: 'Inter',
    fontSize: 14 * SCALE,
    color: '#717171',
    fontWeight: '400',
    lineHeight: 20 * SCALE,
  },
  statsRowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
    paddingHorizontal: 48 * SCALE,
    marginBottom: 16 * SCALE,
  },
  statsRowBottom: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 24 * SCALE,
  },
  statCardSquare: {
    width: 150 * SCALE,
    height: 150 * SCALE,
    borderRadius: 10 * SCALE,
    alignItems: 'center',
    paddingVertical: 16 * SCALE,
    paddingHorizontal: 8 * SCALE,
    marginHorizontal: 8 * SCALE,
    shadowRadius: 4,
    elevation: 2,
  },
  statCardRect: {
    width: 320 * SCALE,
    height: 110 * SCALE,
    borderRadius: 10 * SCALE,
    alignItems: 'center',
    paddingVertical: 16 * SCALE,
    paddingHorizontal: 8 * SCALE,
    elevation: 2,
  },
  squareIconRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginBottom: 8 * SCALE,
    marginTop: 8 * SCALE,
    paddingLeft: 8 * SCALE,
  },
  squareIcon: {
    width: 40 * SCALE,
    height: 40 * SCALE,
  },
  squareLabel: {
    fontFamily: 'Inter',
    fontSize: 13 * SCALE,
    color: '#717171',
    fontWeight: '400',
    marginBottom: 2 * SCALE,
    textAlign: 'left',
    width: '100%',
    paddingLeft: 8 * SCALE,
  },
  squareValue: {
    fontFamily: 'Inter',
    fontSize: 20 * SCALE,
    color: '#717171',
    fontWeight: '600',
    textAlign: 'left',
    width: '100%',
    paddingLeft: 8 * SCALE,
  },
  rectContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    paddingHorizontal: 12 * SCALE,
    paddingVertical: 8 * SCALE,
  },
  rectIcon: {
    width: 40 * SCALE,
    height: 40 * SCALE,
    marginRight: 12 * SCALE,
  },
  rectTextCol: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  rectTitle: {
    fontFamily: 'Inter',
    fontSize: 18 * SCALE,
    color: '#717171',
    fontWeight: '600',
    textAlign: 'left',
  },
  rectSubtitle: {
    fontFamily: 'Inter',
    fontSize: 13 * SCALE,
    color: '#717171',
    fontWeight: '400',
    textAlign: 'left',
  },
  rectValueCol: {
    justifyContent: 'center',
    alignItems: 'flex-end',
    minWidth: 60 * SCALE,
  },
  rectValue: {
    fontFamily: 'Inter',
    fontSize: 22 * SCALE,
    color: '#717171',
    fontWeight: '600',
    textAlign: 'right',
  },
  careContainer: {
    paddingHorizontal: 24 * SCALE,
    marginBottom: 40 * SCALE,
  },
  careTitle: {
    fontFamily: 'Inter',
    fontSize: 18 * SCALE,
    color: '#000',
    fontWeight: 'bold',
    marginBottom: 8 * SCALE,
  },
  careText: {
    fontFamily: 'Inter',
    fontSize: 14 * SCALE,
    color: '#717171',
    fontWeight: '400',
    lineHeight: 20 * SCALE,
  },
  errorText: {
    fontFamily: 'Inter',
    fontSize: 16 * SCALE,
    color: '#717171',
    textAlign: 'center',
    marginTop: 100 * SCALE,
  },
  ctaContainer: {
    paddingHorizontal: 24 * SCALE,
    marginBottom: 40 * SCALE,
    marginTop: 20 * SCALE,
  },
  ctaButton: {
    backgroundColor: '#26CB66',
    borderRadius: 25 * SCALE,
    paddingVertical: 16 * SCALE,
    paddingHorizontal: 32 * SCALE,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  ctaButtonText: {
    fontFamily: 'Inter',
    fontSize: 16 * SCALE,
    color: '#fff',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
});

export default styles; 