/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Connect` | `/Connect`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Dashboard` | `/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Product` | `/Product`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/authen/authen`; params?: Router.UnknownInputParams; } | { pathname: `/styles/authen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/four.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/three.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/two.styles`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Connect` | `/Connect`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Dashboard` | `/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Product` | `/Product`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/authen/authen`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/authen.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/four.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/index.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/three.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/two.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Connect${`?${string}` | `#${string}` | ''}` | `/Connect${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Dashboard${`?${string}` | `#${string}` | ''}` | `/Dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Product${`?${string}` | `#${string}` | ''}` | `/Product${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/authen/authen${`?${string}` | `#${string}` | ''}` | `/styles/authen.styles${`?${string}` | `#${string}` | ''}` | `/styles/four.styles${`?${string}` | `#${string}` | ''}` | `/styles/index.styles${`?${string}` | `#${string}` | ''}` | `/styles/three.styles${`?${string}` | `#${string}` | ''}` | `/styles/two.styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Connect` | `/Connect`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Dashboard` | `/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Product` | `/Product`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/authen/authen`; params?: Router.UnknownInputParams; } | { pathname: `/styles/authen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/four.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/index.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/three.styles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/two.styles`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
