name: Back CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  test:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Skip if server/ does not exist
        run: |
          if [ ! -d "server" ]; then
            echo "server/ directory not found, skipping job."
            exit 0
          fi

      - name: Install dependencies
        working-directory: server
        run: npm ci

      - name: Lint backend
        working-directory: server
        run: npm run lint

      - name: Run tests
        working-directory: server
        run: npm test

