name: Front CI

on:
  push:
    branches:
      - dev/front
      - develop
      - main
    paths:
      - 'my-app/**'
  pull_request:
    paths:
      - 'my-app/**'

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-app

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build
